client/urls.py
from django.urls import path
from .views import (HomeView,ProductDetailView,CartDeteilView,category_books, delete_cart,ProductSallerView,CreateBookView)

app_name='client'

urlpatterns=[
    path('',HomeView.as_view(),name='home'),
    path('product/<int:product_id>/', ProductDetailView.as_view() ,name='deteil'),
    path('category/<int:category_id>/',category_books, name='category_books'),
    path('cart-deteil/', CartDeteilView.as_view(), name='cart_deteil'),
    path('seller-deteil/', ProductSallerView.as_view(), name='dashboard_seller'),
    path('delete-cart/<int:id>/',delete_cart, name='delete_cart'),
    path('add-book/', CreateBookView.as_view(), name='add_book'),

    
   
    
    
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users.views import RegisterView,LoginView,LogoutView
from client.views import (UsersdashView,UpdateUserView,delete,deleteproduct)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('log-out/', LogoutView.as_view(), name='log_out'),
    path('dashboard/', UsersdashView.as_view(), name='dashboard'),
    path('update/<int:id>/', UpdateUserView.as_view(), name='update'),
    path('delete/<int:id>/', delete, name='delete'),
    path('delete-product/<int:id>/', deleteproduct, name='delete_product'),

   
    path('register/', RegisterView.as_view(), name='register'),
    path('', include('client.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import LoginView,RegisterView,ProfileView,LogoutView



urlpatterns = [
    
    
   
    

]

client/models.py
from django.db import models

# Create your models here.

client/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from users.models import Product,Cart,Category
from users.models import User,Product
from users.peremissions import AdminRequiredMixin,SellerRequiredMixin
from users.forms import UpdateUserForm, AddBookForm


class UsersdashView(View):

    def get(self, request):
        user = User.objects.all()
        return render(request, 'dashboard.html', {'users': user})


class HomeView(View):
    def get(self, request):
        product = Product.objects.all()
        categorys=Category.objects.all()
        
        products = Product.objects.filter(in_stock=True)
        cart=Cart.objects.count()
        return render(request, 'client/home.html', context={'products': products,'product': product, 'cart': cart,'categorys':categorys })
def category_books(request, category_id):
    categorys=Category.objects.all()
    category = get_object_or_404(Category, id=category_id)
    product = category.products.all()
    return render(request, 'client/home.html', {'product': product, 'categorys': categorys})
    
class ProductDetailView(View):
    def get(self, request, product_id):
        categorys=Category.objects.all()
        product=get_object_or_404(Product, id=product_id)
        cart=Cart.objects.count()
        return render(request, 'client/deteil.html', context={'product': product, 'cart': cart, 'categorys': categorys})
    def post(self, request,product_id):
        product=get_object_or_404(Product, id=product_id)
        quantity=int(request.POST['cart'])
        if Cart.objects.filter(product=product).exists():
            cart=Cart.objects.filter(product=product).first()
            cart.quantity+=quantity
            cart.save()
        else:
            cart=Cart()
            cart.product=product
            cart.quantity=quantity
            cart.save()
        return redirect('client:home')
    

class CartDeteilView(View):
    def get(self, request):
        categorys=Category.objects.all()
        products=Cart.objects.all()
        cart=Cart.objects.count()
        return render(request, 'client/cart_deteil.html', {'products':products, 'cart':cart, 'categorys':categorys})
    


class UpdateUserView(AdminRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, id=id)
        form = UpdateUserForm(instance=user)  
        return render(request, 'create.html', { 'form': form})
        

    def post(self, request, id):
        user = get_object_or_404(User, id=id)
        form = UpdateUserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():


            form.save()
            return redirect('dashboard')
        return render(request, 'create.html', {'form': form})

def delete(request, id):
    delet = get_object_or_404(User, id=id)
    delet.delete()
    return redirect('dashboard')


def deleteproduct(request, id):
    delet = get_object_or_404(Product, id=id)
    delet.delete()
    return redirect('client:home')



def delete_cart(request, id):
    delet = get_object_or_404(Cart, id=id)
    delet.delete()
    return redirect('client:home')



class ProductSallerView(View):
    def get(self, request):
        product = Product.objects.all()
        return render(request, 'dashboard_seller.html', {'product': product})
    
class CreateBookView(SellerRequiredMixin, View):
    def get(self, request):
        form = AddBookForm()
        return render(request, 'add_book.html', context={"form":form})
    
    def post(self, request):
        form = AddBookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('client:home')
        return render(request, 'add_book.html', {'form': form})

client/templates/client/cart_deteil.html
{% extends 'base.html '%}

{% block content %}

<div class="row">
  <div class="col">
    <div class="tab-content mt-60px">
      <!-- 1st tab start -->
      <div class="tab-pane fade show active" id="tab-jewelry">
        <div class="row">
          {% for product in products %}
          <div class="col-lg-4 col-xl-3 col-md-6 col-sm-6 col-xs-6 mb-30px">
            <!-- Single Prodect -->

            <div class="product">

              <div class="thumb">

                <a href="single-product.html" class="image">
                  <img src="{{product.product.image.url}}" alt="Product" />
                  <img class="hover-image" src="{{product.product.image.url}}" alt="Product" />

                </a>
                <span class="badges">
                  <span class="new">New</span>
                </span>
                <div class="actions">
                  <a href="wishlist.html" class="action wishlist" title="Wishlist"><i class="pe-7s-like"></i></a>
                  <a href="#" class="action quickview" data-link-action="quickview" title="Quick view"
                    data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="pe-7s-look"></i></a>
                  <a href="compare.html" class="action compare" title="Compare"><i class="pe-7s-refresh-2"></i></a>
                </div>
              </div>

              <div class="content">
                <span class="ratings">
                  <span class="rating-wrap">
                    <span class="star" style="width: 100%"></span>
                  </span>
                  <span class="rating-num">( 5 Review )</span>
                </span>
                <h5 class="title"><a href="single-product.html">{{product.product.name}}</a></h5>
                </a>
                </h5>
                <span class="price">
                  <span class="new">${{product.product.price}}</span>
                </span>
                <a class="btn btn-outline-danger" href="{% url 'client:delete_cart' product.id %}">delete</a>
              </div>
            </div>

          </div>
          {% endfor %}
        </div>
        <!-- 6th tab end -->
      </div>
    </div>
  </div>
</div>
{% endblock content %}

client/templates/client/deteil.html
{% extends 'base.html' %}
{% block content %}
<body>
    <!-- Product Details Area Start -->
     
    <div class="product-details-area pt-100px pb-100px">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-sm-12 col-xs-12 mb-lm-30px mb-md-30px mb-sm-30px">
                    <!-- Swiper -->
                    <div class="swiper-container zoom-top">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide zoom-image-hover">
                                <img class="img-responsive m-auto" src="{{product.image.url}}"
                                    alt="">
                            </div>
                            
                        </div>
                    </div>
                    
                </div>
                <div class="col-lg-6 col-sm-12 col-xs-12" data-aos="fade-up" data-aos-delay="200">
                    <div class="product-details-content quickview-content ml-25px">
                        <h2>{{product.name}}</h2>
                        <div class="pricing-meta">
                            <ul class="d-flex">
                                <li class="new-price">${{product.price}}</li>
                                
                            </ul>
                        </div>
                        <div class="pro-details-rating-wrap">
                            <div class="rating-product">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </div>
                            <span class="read-review"><a class="reviews" href="#">( 2 Review )</a></span>
                        </div>
                        <div class="stock mt-30px">
                            <span class="avallabillty">Availability: <span class="in-stock"><i class="fa fa-check"></i>In Stock</span></span>
                        </div>
                        <p class="mt-30px mb-0">{{product.description}} </p>
                        <div class="pro-details-color-size d-flex">
                            <!-- Right Side Start -->
                            <div class="select-shoing-wrap d-flex align-items-center">
                                
                                
                            </div>
                            <!-- Right Side End -->
                            <!-- Right Side Start -->
                            
                            <!-- Right Side End -->
                        </div>
                        <div class="pro-details-quality">
                            <form method="post" >
                                {% csrf_token %}
                                <div class="cart-plus-minus">
                                    <input class="cart-plus-minus-box" type="text" name="cart" value="1" />
                                </div>
                                <div class="pro-details-cart">
                                    <button class="add-cart" href=""> Add To
                                        Cart</button>


                                </div>
                                {% if user.user_role == 'seller' %}
              
                                     <a class="btn btn-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                                 {% endif %}
                            </form>
                            
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
        
    </div>


  






</body>
{% endblock content %}