client/urls.py
from django.urls import path
from .views import (HomeView,ProductDetailView,CartDeteilView,category_books, delete_cart,ProductSallerView,CreateBookView)

app_name='client'

urlpatterns=[
    path('',HomeView.as_view(),name='home'),
    path('product/<int:product_id>/', ProductDetailView.as_view() ,name='deteil'),
    path('category/<int:category_id>/',category_books, name='category_books'),
    path('cart-deteil/', CartDeteilView.as_view(), name='cart_deteil'),
    path('seller-deteil/', ProductSallerView.as_view(), name='dashboard_seller'),
    path('delete-cart/<int:id>/',delete_cart, name='delete_cart'),
    path('add-book/', CreateBookView.as_view(), name='add_book'),

    
   
    
    
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users.views import RegisterView,LoginView,LogoutView
from client.views import (UsersdashView,UpdateUserView,delete,deleteproduct)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('log-out/', LogoutView.as_view(), name='log_out'),
    path('dashboard/', UsersdashView.as_view(), name='dashboard'),
    path('update/<int:id>/', UpdateUserView.as_view(), name='update'),
    path('delete/<int:id>/', delete, name='delete'),
    path('delete-product/<int:id>/', deleteproduct, name='delete_product'),

   
    path('register/', RegisterView.as_view(), name='register'),
    path('', include('client.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import LoginView,RegisterView,ProfileView,LogoutView



urlpatterns = [
    
    
   
    

]

templates/add_book.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Add book page</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="robots" content="index, follow" />
  <title>Mioca - Handmade Goods eCommerce HTML Template</title>
  <meta name="description" content="Mioca - Handmade Goods eCommerce HTML Template" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- Add site Favicon -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon/favicon.ico' %}" type="image/png">


  <!-- vendor css (Icon Font) -->
  <link rel="stylesheet" href="{% static 'assets/css/cart.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.bundle.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/vendor/pe-icon-7-stroke.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/vendor/font.awesome.css' %}" />

  <!-- plugins css (All Plugins Files) -->
  <link rel="stylesheet" href="{% static 'assets/css/plugins/animate.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugins/swiper-bundle.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugins/jquery-ui.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugins/nice-select.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/css/plugins/venobox.css' %}" />

  <!-- Use the minified version files listed below for better performance and remove the files listed above -->
  <!-- <link rel="stylesheet" href="assets/css/vendor/vendor.min.css" />
    <link rel="stylesheet" href="assets/css/plugins/plugins.min.css" />
    <link rel="stylesheet" href="assets/css/style.min.css"> -->

  <!-- Main Style -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />

</head>

<body>


  <!-- Header Area Start -->
  <header>
    <div class="header-main sticky-nav ">
      <div class="container position-relative">
        <div class="row">
          <div class="col-auto align-self-center">
            <div class="header-logo">
              <a href="index.html"><img src="{% static 'assets/images/logo/logo.png' %}" alt="Site Logo" /></a>
            </div>
          </div>
          <div class="col align-self-center d-none d-lg-block">
            <div class="main-menu">
              <ul>
                <li><a href="{% url 'client:home' %}">Home</a>

                </li>

                <li class="dropdown position-static"><a>Category <i class="fa fa-angle-down"></i></a>
                  <ul class="mega-menu d-block">
                    {% for cat in categorys %}
                    <li class="d-flex">
                      
                      <ul class="d-block">
                        <li><a href="{% url 'client:category_books' cat.id %}">{{ cat.name }}</a></li>
                      </ul>
                      
                      
                    </li>
                    
                    &nbsp;{% endfor %}
                    {% if user.user_role == 'users' %}


                    </li>
                    <ul class="d-block">
                      <li><a href="{% url 'dashboard' %}">Tabless</a></li>
                    </ul>
                    {% endif %}       
              </ul>





                  

              </li>
              {% if user.user_role == 'seller' %}


                        </li>
                        
                        <ul class="ms-5">
                          <li><a href="{% url 'client:add_book' %}">Creat book</a></li>
                        </ul>
              {% endif %}

            </div>
          </div>
          <!-- Header Action Start -->
          <div class="col col-lg-auto align-self-center pl-0">
            <div class="header-actions">
              <!-- Single Wedge Start -->
              <a href="#" class="header-action-btn" data-bs-toggle="modal" data-bs-target="#searchActive">
                <i class="pe-7s-search"></i>
              </a>
              <!-- Single Wedge End -->
              <div class="header-bottom-set dropdown">
                <button class="dropdown-toggle header-action-btn" data-bs-toggle="dropdown"><i
                    class="pe-7s-users"></i></button>
                <ul class="dropdown-menu dropdown-menu-right">

                  <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                  <li><a class="dropdown-item" href="{% url 'login' %}">Log in</a></li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">

                    <a class="nav-link active" aria-current="page" href="{% url 'log_out' %}">Log Out</a>
                  </li>
                  {% endif %}

                  {% if user.user_role == 'users' %}

                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
                  </li>
                  {% endif %}

                </ul>
              </div>
              <!-- Single Wedge Start -->

              <!-- Single Wedge End -->
              <form class="d-flex">
                <a class="btn btn-outline-dark" href="{% url 'client:cart_deteil' %}">
                  <i class="pe-7s-shopbag"></i>
                  <span class="header-action-num">{{cart}}</span>
                  <!-- <span class="cart-amount">€30.00</span> -->
                </a>
              </form>
              <a href="" class="header-action-btn header-action-btn-menu offcanvas-toggle d-lg-none">
                <i class="pe-7s-menu"></i>
              </a>
            </div>
            <!-- Header Action End -->
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Header Area End -->
  <div class="offcanvas-overlay"></div>

  {% block content %}

  {% endblock content %}
  <!-- Footer -->
  <footer class="text-center text-lg-start bg-body-tertiary text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->

      <!-- Left -->

      <!-- Right -->

      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
  <!-- Modal end -->

  <!-- Global Vendor, plugins JS -->

  <!-- Vendor JS -->
  <script src="{% static 'assets/js/vendor/jquery-3.5.1.min.js' %}"></script>

  <script src="{% static 'assets/js/vendor/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/vendor/jquery-migrate-3.3.0.min.js' %}"></script>
  <script src="{% static 'assets/js/vendor/modernizr-3.11.2.min.js' %}"></script>

  <!--Plugins JS-->
  <script src="{% static 'assets/js/plugins/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery-ui.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/countdown.js' %}"></script>
  <script src="{% static 'assets/js/plugins/scrollup.js' %}"></script>
  <script src="{% static 'assets/js/plugins/jquery.zoom.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/venobox.min.js' %}"></script>
  <script src="{% static 'assets/js/plugins/ajax-mail.js' %}"></script>

  <!-- Use the minified version files listed below for better performance and remove the files listed above -->
  <!-- <script src="assets/js/vendor/vendor.min.js"></script>
    <script src="assets/js/plugins/plugins.min.js"></script> -->

  <!-- Main Js -->
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>

</html>

templates/create.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Create or edit product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>


{% endblock content %}

templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-dark table-striped">
    
 
        <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
            <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>User Role</th>
            
            <th>Update/delete</th>
            
            </tr>
        </thead>
        {% for user in users %}
        <tbody>
            <tr>
            <td>
                
                    
                    <p class="fw-bold mb-1">{{user.username}}</p>
                    
                
            </td>
            <td>
                <p class="fw-bold mb-1">{{user.first_name}} {{user.last_name}}</p>
                
                
            </td>
            <td>
                <p class="fw-bold mb-1">{{user.user_role}}</p>
                
                
            </td>
            
                
                
            <td>
                    <a class="btn btn-danger" href="{% url 'delete' user.id %}">Delete</a>
                    <a  class="btn btn-info" href="{% url 'update' user.id  %}">Update</a>
            </td>
                
            
            {% endfor %}
            </tr>
    
  
  

    </table>
{% endblock content %}

templates/dashboard_seller.html
{% extends 'base.html' %}

{% block content %}
    
    <table class="table table-dark table-striped">
    
 
        <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
            <tr>
            <th>KITOB NOMI</th>
            <th>NARXI</th>
            <th>ADABIYOT TURI</th>
            
            
            
            </tr>
        </thead>
        {% for user in product %}
        <tbody>
            <tr>
            <td>
                
                    
                    <p class="fw-bold mb-1">{{user.name}}</p>
                    
                
            </td>
            <td>
                <p class="fw-bold mb-1">{{user.price}}</p>
                
                
            </td>
            <td>
                <p class="fw-bold mb-1">{{user.category}}</p>
                
                
            </td>
            
                
                
            
                
            
            {% endfor %}
            </tr>
    
  
  

    </table>
{% endblock content %}

templates/log_out.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Login page</h1>

<form  method="post" >
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-outline-info">Log in</button>
</form>
</div>


{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Login page</h1>

<form  method="post" >
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-outline-info">Log in</button>
</form>
</div>


{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Register page</h1>

<form  method="post" >
    {% csrf_token %}

    {{form}}

    <button type="submit" class="btn btn-outline-info">Log in</button>
</form>
</div>


{% endblock content %}